version: 2.1

orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.2.4

jobs:
  test:
    parameters:
      version:
        default: "stable"
        description: Node.JS version to install
        type: string
    docker:
      - image: cimg/node:<<parameters.version>>-browsers
    resource_class: large
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          install-geckodriver: false
      - run: npm install
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Test that build is successful"
          command: npm run build
      - run: npm run test:ci

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run: npx semantic-release

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              version:
                - "current"
                - "lts"

      - deploy:
          requires:
            - test
